countries_dict = {
  'ES': ['Spain', 36, 38],
  'EG': ['Egypt', 2, 2],
  'GR': ['Greece', 3, 3],
  'MT': ['Malta', 7, 8],
  'PT': ['Portugal', 10, 12],
  'KZ': ['Kazakhstan', 16, 16],
  'MA': ['Morocco', 2, 3],
  'CZ': ['Czech Republic', 5, 5],
  'HU': ['Hungary', 1, 1],
  'FI': ['Finland', 14, 15],
  'GB': ['United Kingdom', 3, 3],
  'BY': ['Belarus', 1, 1],
  'CH': ['Switzerland', 12, 12],
  'RU': ['Russia', 107, 112],
  'AT': ['Austria', 2, 2],
  'MN': ['Mongolia', 1, 1],
  'LI': ['Liechtenstein', 1, 1],
  'IT': ['Italy', 4, 4]
}
