countries_dict = {
  'CH': ['Switzerland', 2, 3],
  'ES': ['Spain', 8, 20],
  'VA': ['Vatican City', 1, 2],
  'ZA': ['South Africa', 4, 7],
  'IT': ['Italy', 10, 13],
  'DK': ['Denmark', 5, 6],
  'AU': ['Australia', 19, 78],
  'CN': ['South China Sea Islands (disputed)', 6, 8],
  'BE': ['Belgium', 106, 133],
  'MY': ['Malaysia', 5, 12],
  'IE': ['Ireland', 3, 3],
  'AT': ['Austria', 7, 9],
  'PT': ['Portugal', 10, 11],
  'TH': ['Thailand', 6, 9],
  'SG': ['Singapore', 5, 7],
  'DE': ['Germany', 2, 3],
  'CA': ['Canada', 7, 7],
  'MT': ['Malta', 2, 2],
  'GB': ['United Kingdom', 5, 7],
  'CL': ['Chile', 2, 2],
  'IN': ['India', 25, 65],
  'LU': ['Luxembourg', 3, 5],
  'PL': ['Poland', 1, 1],
  'US': ['United States of America', 21, 86],
  'NL': ['Netherlands', 318, 386],
  'RU': ['Russia', 5, 5],
  'FR': ['France', 107, 148],
  'AE': ['United Arab Emirates', 1, 1],
  'JP': ['Japan', 8, 18]
}
