var countries = [
  ['NL', 'The Netherlands', 105, 176],
  ['JP', 'Japan', 6, 20],
  ['BE', 'Belgium', 52, 76],
  ['FR', 'France', 86, 141],
  ['US', 'United States of America', 18, 103],
  ['GB', 'United Kingdom', 4, 8],
  ['ES', 'Spain', 6, 35],
  ['DK', 'Denmark', 2, 3],
  ['SG', 'Singapore', 4, 21],
  ['CA', 'Canada', 4, 13],
  ['PT', 'Portugal', 9, 14],
  ['PL', 'Poland', 1, 10],
  ['LU', 'Luxembourg', 2, 4],
  ['CH', 'Switzerland', 3, 10],
  ['AT', 'Austria', 6, 18],
  ['TH', 'Thailand', 8, 21],
  ['DE', 'Germany', 2, 5],
  ['AU', 'Australia', 17, 125],
  ['IN', 'India', 25, 67],
  ['IT', 'Italy', 8, 10],
  ['RU', 'Russia', 5, 5],
  ['MT', 'Malta', 2, 2],
  ['CN', 'China', 4, 6],
  ['IE', 'Ireland', 1, 1],
  ['MY', 'Malaysia', 4, 12],
  ['VA', 'Vatican City', 1, 2],
  ['CL', 'Chile', 2, 2],
  ['ZA', 'South Africa', 3, 6]
]
