countries_dict = {
  'CL': ['Chile', 2, 2],
  'DE': ['Germany', 2, 3],
  'VA': ['Vatican City', 1, 2],
  'BE': ['Belgium', 487, 586],
  'CA': ['Canada', 18, 19],
  'MY': ['Malaysia', 5, 9],
  'IN': ['India', 32, 71],
  'AU': ['Australia', 21, 39],
  'AT': ['Austria', 8, 10],
  'RU': ['Russia', 5, 5],
  'IE': ['Ireland', 3, 3],
  'MT': ['Malta', 2, 2],
  'JP': ['Japan', 10, 16],
  'LU': ['Luxembourg', 18, 20],
  'TH': ['Thailand', 4, 4],
  'IT': ['Italy', 14, 17],
  'NL': ['Netherlands', 1227, 1470],
  'SG': ['Singapore', 4, 5],
  'AE': ['United Arab Emirates', 1, 1],
  'AR': ['Argentina', 1, 1],
  'GB': ['United Kingdom', 6, 8],
  'US': ['United States of America', 22, 59],
  'ZA': ['South Africa', 4, 7],
  'DK': ['Denmark', 9, 11],
  'CN': ['South China Sea Islands (disputed)', 8, 10],
  'CH': ['Switzerland', 2, 3],
  'ES': ['Spain', 6, 8],
  'PT': ['Portugal', 14, 15],
  'PL': ['Poland', 1, 1],
  'FR': ['France', 401, 568]
}
