countries_dict = {
  'MY': ['Malaysia', 2, 5],
  'IL': ['Israel', 4, 6],
  'RU': ['Russia', 12, 36],
  'CU': ['Cuba', 7, 10],
  'ES': ['Spain', 9, 19],
  'VN': ['Vietnam', 4, 6],
  'GR': ['Greece', 2, 2],
  'MC': ['Monaco', 1, 1],
  'TR': ['Turkey', 2, 3],
  'NO': ['Norway', 2, 5],
  'FR': ['France', 2, 4],
  'IT': ['Italy', 6, 15],
  'HU': ['Hungary', 2, 3],
  'CY': ['Cyprus', 1, 2],
  'BR': ['Brazil', 3, 7],
  'CN': ['South China Sea Islands (disputed)', 1, 4],
  'PT': ['Portugal', 2, 4],
  'SE': ['Sweden', 2, 2],
  'TH': ['Thailand', 6, 10],
  'MA': ['Morocco', 2, 4],
  'NL': ['The Netherlands', 1, 1],
  'AE': ['United Arab Emirates', 1, 1],
  'GB': ['United Kingdom', 1, 2]
}
