countries_dict = {
  'MA': ['Morocco', 4, 6],
  'AT': ['Austria', 1, 1],
  'FI': ['Finland', 1, 1],
  'NO': ['Norway', 6, 11],
  'NL': ['The Netherlands', 1, 1],
  'CY': ['Cyprus', 1, 3],
  'TR': ['Turkey', 3, 7],
  'IL': ['Israel', 4, 6],
  'AR': ['Argentina', 1, 2],
  'CU': ['Cuba', 11, 19],
  'FR': ['France', 3, 6],
  'AE': ['United Arab Emirates', 1, 1],
  'GR': ['Greece', 3, 4],
  'VA': ['Vatican City', 1, 2],
  'HU': ['Hungary', 2, 3],
  'CN': ['South China Sea Islands (disputed)', 2, 7],
  'VN': ['Vietnam', 4, 9],
  'GB': ['United Kingdom', 2, 5],
  'MY': ['Malaysia', 3, 6],
  'HR': ['Croatia', 1, 1],
  'MC': ['Monaco', 1, 1],
  'IT': ['Italy', 7, 18],
  'TH': ['Thailand', 11, 22],
  'PT': ['Portugal', 3, 5],
  'BR': ['Brazil', 3, 9],
  'RU': ['Russia', 15, 42],
  'ES': ['Spain', 12, 22],
  'SE': ['Sweden', 2, 3]
}
