countries_dict = {
  'GR': ['Greece', 5, 8],
  'HU': ['Hungary', 2, 3],
  'MC': ['Monaco', 1, 1],
  'CN': ['South China Sea Islands (disputed)', 3, 10],
  'RU': ['Russia', 27, 67],
  'CU': ['Cuba', 12, 23],
  'VA': ['Vatican City', 1, 2],
  'NL': ['The Netherlands', 1, 1],
  'IT': ['Italy', 10, 28],
  'FI': ['Finland', 1, 1],
  'PT': ['Portugal', 3, 5],
  'BR': ['Brazil', 3, 12],
  'IL': ['Israel', 4, 6],
  'EG': ['Egypt', 1, 1],
  'UZ': ['Uzbekistan', 5, 8],
  'AT': ['Austria', 1, 1],
  'TH': ['Thailand', 14, 30],
  'MX': ['Mexico', 2, 5],
  'SE': ['Sweden', 3, 4],
  'VN': ['Vietnam', 4, 15],
  'FR': ['France', 3, 8],
  'MY': ['Malaysia', 3, 11],
  'NO': ['Norway', 6, 11],
  'AE': ['United Arab Emirates', 1, 1],
  'HR': ['Croatia', 2, 2],
  'GB': ['United Kingdom', 2, 6],
  'TR': ['Turkey', 3, 8],
  'MA': ['Morocco', 4, 6],
  'AR': ['Argentina', 1, 2],
  'ES': ['Spain', 12, 23],
  'CY': ['Cyprus', 1, 4]
}
