var countries = [
  ['GB', 'United Kingdom', 223, 421],
  ['AE', 'United Arab Emirates', 9, 9],
  ['VG', 'British Virgin Islands', 24, 52],
  ['IE', 'Ireland', 4, 7],
  ['US', 'United States of America', 40, 105],
  ['EG', 'Egypt', 7, 13],
  ['BE', 'Belgium', 30, 46],
  ['CZ', 'Czech Republic', 6, 13],
  ['NL', 'The Netherlands', 3, 6],
  ['AT', 'Austria', 6, 8],
  ['IT', 'Italy', 37, 46],
  ['VA', 'Vatican City', 4, 6],
  ['GR', 'Greece', 2, 3],
  ['DK', 'Denmark', 5, 5],
  ['SE', 'Sweden', 1, 2],
  ['EE', 'Estonia', 1, 1],
  ['RU', 'Russia', 1, 1],
  ['FR', 'France', 14, 32],
  ['NO', 'Norway', 8, 10],
  ['ES', 'Spain', 12, 45],
  ['PT', 'Portugal', 5, 6],
  ['GI', 'Gibraltar', 2, 3],
  ['SG', 'Singapore', 6, 13],
  ['BN', 'Brunei Darussalam', 3, 4],
  ['VN', 'Vietnam', 12, 19],
  ['KH', 'Cambodia', 4, 7],
  ['TH', 'Thailand', 6, 12],
  ['DE', 'Germany', 20, 45],
  ['LU', 'Luxembourg', 6, 8],
  ['MX', 'Mexico', 4, 28],
  ['HN', 'Honduras', 3, 6],
  ['GT', 'Guatemala', 1, 1],
  ['MC', 'Monaco', 3, 8],
  ['HU', 'Hungary', 12, 20]
]
