var countries = [
  ['HR', 'Croatia', 3, 9],
  ['IN', 'India', 2, 4],
  ['GB', 'United Kingdom', 277, 519],
  ['RS', 'Serbia', 1, 1],
  ['CN', 'China', 15, 18],
  ['MY', 'Malaysia', 5, 5],
  ['ID', 'Indonesia', 8, 9],
  ['CA', 'Canada', 138, 160],
  ['US', 'United States of America', 62, 69],
  ['SG', 'Singapore', 5, 6],
  ['TH', 'Thailand', 4, 4],
  ['IT', 'Italy', 4, 5],
  ['FR', 'France', 18, 19],
  ['DE', 'Germany', 12, 14],
  ['BE', 'Belgium', 1, 1],
  ['XK', 'Kosovo', 2, 2],
  ['BA', 'Bosnia and Herzegovina', 3, 3],
  ['NP', 'Nepal', 17, 24],
  ['BS', 'Bahamas', 1, 1],
  ['GR', 'Greece', 1, 1],
  ['RU', 'Russia', 4, 4],
  ['SE', 'Sweden', 1, 1],
  ['MA', 'Morocco', 4, 4],
  ['PT', 'Portugal', 1, 1],
  ['NL', 'The Netherlands', 3, 3],
  ['NO', 'Norway', 2, 2],
  ['DK', 'Denmark', 4, 4],
  ['FI', 'Finland', 5, 5],
  ['IE', 'Ireland', 5, 5],
  ['ES', 'Spain', 1, 1],
  ['FO', 'Faroe Islands', 6, 6],
  ['VN', 'Vietnam', 1, 1],
  ['MC', 'Monaco', 2, 2],
  ['ME', 'Montenegro', 1, 1]
]
