countries_dict = {
  'SG': ['Singapore', 5, 6],
  'ME': ['Montenegro', 1, 1],
  'RS': ['Serbia', 1, 1],
  'FO': ['Faroe Islands', 6, 6],
  'FI': ['Finland', 5, 5],
  'BS': ['Bahamas', 1, 1],
  'NO': ['Norway', 2, 2],
  'ID': ['Indonesia', 8, 9],
  'FR': ['France', 18, 19],
  'PT': ['Portugal', 1, 1],
  'SE': ['Sweden', 2, 2],
  'IE': ['Ireland', 7, 7],
  'XK': ['Kosovo', 2, 2],
  'CA': ['Canada', 155, 180],
  'GB': ['United Kingdom', 290, 536],
  'TH': ['Thailand', 4, 4],
  'MA': ['Morocco', 4, 4],
  'IN': ['India', 2, 4],
  'DE': ['Germany', 14, 16],
  'ES': ['Spain', 1, 1],
  'BA': ['Bosnia and Herzegovina', 3, 3],
  'VN': ['Vietnam', 1, 1],
  'NP': ['Nepal', 19, 26],
  'CN': ['South China Sea Islands (disputed)', 15, 18],
  'IT': ['Italy', 5, 6],
  'BE': ['Belgium', 1, 1],
  'HR': ['Croatia', 3, 9],
  'MC': ['Monaco', 2, 2],
  'DK': ['Denmark', 4, 4],
  'US': ['United States of America', 68, 75],
  'RU': ['Russia', 4, 4],
  'GR': ['Greece', 1, 1],
  'NL': ['The Netherlands', 3, 3],
  'MY': ['Malaysia', 5, 5]
}
