countries_dict = {
  'PL': ['Poland', 1, 1],
  'NZ': ['New Zealand', 1, 2],
  'JP': ['Japan', 13, 16],
  'US': ['United States of America', 39, 42],
  'FR': ['France', 15, 20],
  'BS': ['Bahamas', 2, 9],
  'AU': ['Australia', 32, 47],
  'IT': ['Italy', 225, 356],
  'IE': ['Ireland', 20, 25],
  'CA': ['Canada', 4, 4],
  'HR': ['Croatia', 1, 1],
  'RO': ['Romania', 6, 6],
  'DE': ['Germany', 5, 8],
  'ES': ['Spain', 15, 22],
  'LK': ['Sri Lanka', 1, 1],
  'TR': ['Turkey', 3, 6],
  'GB': ['United Kingdom', 9, 16],
  'CN': ['South China Sea Islands (disputed)', 18, 19],
  'MX': ['Mexico', 6, 7],
  'GI': ['Gibraltar', 1, 1],
  'KR': ['South Korea', 2, 5],
  'LT': ['Lithuania', 1, 2],
  'RU': ['Russia', 4, 13],
  'BE': ['Belgium', 2, 2],
  'LV': ['Latvia', 2, 9],
  'GR': ['Greece', 19, 31],
  'EE': ['Estonia', 1, 1],
  'NL': ['The Netherlands', 1, 2],
  'KZ': ['Kazakhstan', 3, 4],
  'CH': ['Switzerland', 10, 11],
  'AT': ['Austria', 1, 1]
}
