countries_dict = {
  'NL': ['The Netherlands', 3, 6],
  'GI': ['Gibraltar', 2, 3],
  'VA': ['Vatican City', 4, 6],
  'AE': ['United Arab Emirates', 9, 9],
  'AT': ['Austria', 6, 8],
  'VG': ['British Virgin Islands', 24, 52],
  'IT': ['Italy', 37, 46],
  'HU': ['Hungary', 12, 20],
  'VN': ['Vietnam', 12, 19],
  'BN': ['Brunei Darussalam', 3, 4],
  'SG': ['Singapore', 6, 13],
  'EE': ['Estonia', 1, 1],
  'DE': ['Germany', 20, 45],
  'FR': ['France', 14, 32],
  'RU': ['Russia', 1, 1],
  'BE': ['Belgium', 30, 46],
  'CZ': ['Czech Republic', 6, 13],
  'GB': ['United Kingdom', 224, 423],
  'EG': ['Egypt', 7, 13],
  'ES': ['Spain', 12, 45],
  'SE': ['Sweden', 1, 2],
  'LU': ['Luxembourg', 6, 8],
  'US': ['United States of America', 40, 105],
  'GT': ['Guatemala', 1, 1],
  'DK': ['Denmark', 5, 5],
  'KH': ['Cambodia', 4, 7],
  'MX': ['Mexico', 4, 28],
  'HN': ['Honduras', 3, 6],
  'MC': ['Monaco', 3, 8],
  'GR': ['Greece', 2, 3],
  'IE': ['Ireland', 4, 7],
  'PT': ['Portugal', 5, 6],
  'TH': ['Thailand', 6, 12],
  'NO': ['Norway', 8, 10]
}
