countries_dict = {
  'NI': ['Nicaragua', 1, 1],
  'TW': ['Taiwan', 2, 2],
  'OM': ['Oman', 4, 4],
  'NL': ['Netherlands', 9, 9],
  'CR': ['Costa Rica', 1, 1],
  'TR': ['Turkey', 6, 7],
  'MX': ['Mexico', 2, 2],
  'AT': ['Austria', 8, 8],
  'HR': ['Croatia', 2, 2],
  'SE': ['Sweden', 1, 1],
  'DE': ['Germany', 9, 9],
  'AU': ['Australia', 8, 9],
  'HU': ['Hungary', 6, 6],
  'CN': ['South China Sea Islands (disputed)', 22, 23],
  'BE': ['Belgium', 2, 2],
  'US': ['United States', 35, 36],
  'FI': ['Finland', 1, 1],
  'CZ': ['Czechia', 9, 9],
  'TH': ['Thailand', 2, 2],
  'IN': ['India', 7, 7],
  'PA': ['Panama', 1, 1],
  'PL': ['Poland', 4, 5],
  'CO': ['Colombia', 1, 1],
  'SK': ['Slovakia', 4, 4],
  'ES': ['Spain', 6, 6],
  'VN': ['Vietnam', 1, 1],
  'SG': ['Singapore', 2, 2],
  'KZ': ['Kazakhstan', 4, 4],
  'GB': ['United Kingdom', 7, 7],
  'IT': ['Italy', 6, 6],
  'AE': ['United Arab Emirates', 3, 3],
  'GT': ['Guatemala', 1, 2],
  'RU': ['Russia', 1, 1],
  'MA': ['Morocco', 1, 1],
  'KW': ['Kuwait', 1, 1],
  'IE': ['Ireland', 1, 1],
  'GR': ['Greece', 3, 3],
  'FR': ['France', 7, 7]
}
