countries_dict = {
  'IL': ['Israel', 1, 1],
  'IT': ['Italy', 28, 29],
  'CZ': ['Czech Republic', 2, 2],
  'AT': ['Austria', 1, 1],
  'EE': ['Estonia', 1, 1],
  'IS': ['Iceland', 4, 4],
  'SI': ['Slovenia', 3, 5],
  'PT': ['Portugal', 7, 8],
  'TR': ['Turkey', 1, 1],
  'RO': ['Romania', 5, 5],
  'FR': ['France', 35, 40],
  'NZ': ['New Zealand', 1, 1],
  'AR': ['Argentina', 1, 1],
  'CH': ['Switzerland', 3, 3],
  'HR': ['Croatia', 2, 2],
  'BT': ['Bhutan', 4, 9],
  'ES': ['Spain', 15, 17],
  'IN': ['India', 32, 44],
  'PL': ['Poland', 4, 4],
  'VN': ['Vietnam', 3, 7],
  'CN': ['China', 3, 11],
  'NP': ['Nepal', 1, 4],
  'MY': ['Malaysia', 5, 6],
  'BE': ['Belgium', 10, 10],
  'HU': ['Hungary', 6, 6],
  'CR': ['Costa Rica', 2, 2],
  'NL': ['The Netherlands', 1, 1],
  'US': ['United States of America', 3, 6],
  'GR': ['Greece', 6, 6],
  'MA': ['Morocco', 5, 6],
  'GB': ['United Kingdom', 275, 294],
  'ID': ['Indonesia', 1, 1],
  'MM': ['Myanmar', 8, 16],
  'MG': ['Madagascar', 7, 13]
}
