countries_dict = {
  'BS': ['The Bahamas', 1, 23],
  'HR': ['Croatia', 38, 200],
  'DE': ['Germany', 237, 1065],
  'ME': ['Montenegro', 1, 1],
  'MX': ['Mexico', 2, 2],
  'GB': ['United Kingdom', 34, 115],
  'CZ': ['Czechia', 1, 1],
  'FR': ['France', 14, 19],
  'CA': ['Canada', 8, 35],
  'CU': ['Cuba', 1, 1],
  'CH': ['Switzerland', 10, 31],
  'PT': ['Portugal', 1, 1],
  'DK': ['Denmark', 2, 2],
  'LU': ['Luxembourg', 3, 13],
  'IE': ['Ireland', 2, 12],
  'NL': ['Netherlands', 8, 52],
  'AT': ['Austria', 10, 25],
  'ES': ['Spain', 9, 34],
  'US': ['United States of America', 52, 188],
  'MT': ['Malta', 1, 1],
  'BE': ['Belgium', 4, 5],
  'IT': ['Italy', 102, 370],
  'SE': ['Sweden', 1, 6],
  'AU': ['Australia', 1, 1],
  'KR': ['South Korea', 1, 1],
  'PA': ['Panama', 1, 1],
  'PL': ['Poland', 2, 2],
  'UA': ['Ukraine', 1, 1],
  'SI': ['Slovenia', 3, 42],
  'CN': ['South China Sea Islands (disputed)', 4, 6],
  'MC': ['Monaco', 1, 1]
}
