countries_dict = {
  'SE': ['Sweden', 3, 3],
  'RU': ['Russia', 5, 5],
  'TH': ['Thailand', 1, 1],
  'BM': ['Bermuda', 1, 2],
  'GI': ['Gibraltar', 1, 1],
  'CN': ['South China Sea Islands (disputed)', 1, 9],
  'PT': ['Portugal', 4, 6],
  'AT': ['Austria', 15, 21],
  'IT': ['Italy', 156, 344],
  'ES': ['Spain', 18, 42],
  'PL': ['Poland', 2, 3],
  'NO': ['Norway', 9, 11],
  'DE': ['Germany', 467, 907],
  'IS': ['Iceland', 3, 3],
  'BS': ['The Bahamas', 2, 7],
  'ZA': ['South Africa', 1, 1],
  'FI': ['Finland', 2, 3],
  'NZ': ['New Zealand', 2, 2],
  'PA': ['Panama', 1, 1],
  'MX': ['Mexico', 1, 1],
  'KR': ['South Korea', 1, 1],
  'JE': ['Jersey', 1, 3],
  'CY': ['Cyprus', 1, 1],
  'BE': ['Belgium', 9, 20],
  'NL': ['Netherlands', 12, 34],
  'DK': ['Denmark', 6, 20],
  'IE': ['Ireland', 3, 12],
  'FR': ['France', 31, 46],
  'GB': ['United Kingdom', 71, 148],
  'HR': ['Croatia', 41, 137],
  'AU': ['Australia', 10, 12],
  'GG': ['Guernsey', 2, 2],
  'LU': ['Luxembourg', 2, 4],
  'CA': ['Canada', 19, 32],
  'UG': ['Uganda', 1, 1],
  'CU': ['Cuba', 1, 1],
  'AL': ['Albania', 1, 4],
  'AD': ['Andorra', 1, 1],
  'GR': ['Greece', 2, 3],
  'GL': ['Greenland', 1, 2],
  'CZ': ['Czechia', 2, 3],
  'SI': ['Slovenia', 7, 16],
  'CH': ['Switzerland', 26, 58],
  'JP': ['Japan', 3, 5],
  'US': ['United States of America', 199, 290],
  'HU': ['Hungary', 2, 7],
  'BR': ['Brazil', 1, 1],
  'MT': ['Malta', 1, 1]
}
