countries_dict = {
  'IN': ['India', 7, 7],
  'AG': ['Antigua and Barbuda', 1, 1],
  'VC': ['Saint Vincent and the Grenadines', 1, 1],
  'HN': ['Honduras', 4, 5],
  'IT': ['Italy', 30, 30],
  'BE': ['Belgium', 2, 2],
  'FR': ['France', 22, 23],
  'GB': ['United Kingdom', 1821, 1925],
  'US': ['United States of America', 71, 74],
  'SG': ['Singapore', 9, 12],
  'ES': ['Spain', 28, 32],
  'LC': ['Saint Lucia', 3, 3],
  'HT': ['Haiti', 5, 6],
  'PT': ['Portugal', 3, 3],
  'OM': ['Oman', 2, 2],
  'AE': ['United Arab Emirates', 3, 3],
  'BS': ['Bahamas', 2, 2],
  'NO': ['Norway', 1, 1],
  'NL': ['The Netherlands', 3, 3],
  'BB': ['Barbados', 3, 3],
  'HR': ['Croatia', 15, 15],
  'PK': ['Pakistan', 1, 1],
  'GG': ['Guernsey', 3, 3],
  'MT': ['Malta', 38, 38],
  'GR': ['Greece', 27, 27],
  'MY': ['Malaysia', 1, 1],
  'MX': ['Mexico', 109, 121],
  'CU': ['Cuba', 4, 5]
}
