countries_dict = {
  'BB': ['Barbados', 4, 4],
  'BS': ['Bahamas', 9, 10],
  'LC': ['Saint Lucia', 3, 3],
  'HT': ['Haiti', 5, 6],
  'ES': ['Spain', 37, 43],
  'BE': ['Belgium', 2, 2],
  'NO': ['Norway', 1, 1],
  'SG': ['Singapore', 9, 12],
  'IN': ['India', 7, 7],
  'IT': ['Italy', 30, 30],
  'GG': ['Guernsey', 3, 3],
  'NL': ['The Netherlands', 3, 3],
  'CU': ['Cuba', 5, 6],
  'PT': ['Portugal', 3, 3],
  'US': ['United States of America', 71, 76],
  'HN': ['Honduras', 4, 5],
  'GB': ['United Kingdom', 1845, 1957],
  'MY': ['Malaysia', 1, 1],
  'VC': ['Saint Vincent and the Grenadines', 1, 1],
  'MT': ['Malta', 38, 38],
  'FR': ['France', 23, 24],
  'OM': ['Oman', 2, 2],
  'AG': ['Antigua and Barbuda', 1, 1],
  'PK': ['Pakistan', 1, 1],
  'AE': ['United Arab Emirates', 3, 3],
  'HR': ['Croatia', 15, 15],
  'MX': ['Mexico', 109, 121],
  'GR': ['Greece', 27, 27]
}
