countries_dict = {
  'AE': ['United Arab Emirates', 1, 1],
  'PL': ['Poland', 40, 42],
  'SE': ['Sweden', 3, 3],
  'BI': ['Burundi', 8, 8],
  'TL': ['East Timor', 1, 1],
  'KE': ['Kenya', 1, 1],
  'NL': ['Netherlands', 28, 29],
  'IE': ['Ireland', 26, 27],
  'TO': ['Tonga', 5, 5],
  'GL': ['Greenland', 2, 2],
  'ES': ['Spain', 1, 1],
  'GB': ['United Kingdom', 31, 33],
  'PK': ['Pakistan', 4, 4],
  'OM': ['Oman', 2, 2],
  'AU': ['Australia', 305, 332],
  'FJ': ['Fiji', 1, 1],
  'DK': ['Denmark', 9, 9],
  'FI': ['Finland', 7, 7],
  'SB': ['Solomon Islands', 33, 38],
  'BE': ['Belgium', 32, 34],
  'US': ['United States of America', 10, 10],
  'CA': ['Canada', 1, 1],
  'KR': ['South Korea', 2, 2],
  'ZM': ['Zambia', 1, 1],
  'DE': ['Germany', 91, 96],
  'CN': ['South China Sea Islands (disputed)', 3, 3],
  'VU': ['Vanuatu', 8, 8],
  'ZA': ['South Africa', 1, 1],
  'NZ': ['New Zealand', 23, 23],
  'UG': ['Uganda', 1, 1],
  'TR': ['Turkey', 74, 84],
  'ID': ['Indonesia', 31, 32],
  'CK': ['Cook Islands', 3, 3],
  'SG': ['Singapore', 13, 15]
}
