countries_dict = {
  'NL': ['Netherlands', 26, 26],
  'OM': ['Oman', 2, 2],
  'VU': ['Vanuatu', 8, 8],
  'TR': ['Turkey', 66, 75],
  'ZA': ['South Africa', 1, 1],
  'GB': ['United Kingdom', 30, 31],
  'TO': ['Tonga', 7, 7],
  'PK': ['Pakistan', 4, 4],
  'BI': ['Burundi', 9, 9],
  'AE': ['United Arab Emirates', 1, 1],
  'KE': ['Kenya', 1, 1],
  'SB': ['Solomon Islands', 33, 37],
  'GL': ['Greenland', 2, 2],
  'SE': ['Sweden', 3, 3],
  'TL': ['East Timor', 1, 1],
  'SG': ['Singapore', 13, 15],
  'ZM': ['Zambia', 1, 1],
  'DK': ['Denmark', 9, 9],
  'BE': ['Belgium', 31, 34],
  'CN': ['South China Sea Islands (disputed)', 3, 3],
  'KR': ['South Korea', 3, 3],
  'ID': ['Indonesia', 31, 32],
  'DE': ['Germany', 90, 95],
  'NZ': ['New Zealand', 25, 25],
  'CK': ['Cook Islands', 3, 3],
  'IE': ['Ireland', 25, 26],
  'FJ': ['Fiji', 1, 1],
  'US': ['United States of America', 10, 10],
  'CA': ['Canada', 1, 1],
  'UG': ['Uganda', 1, 1],
  'AU': ['Australia', 349, 373],
  'FI': ['Finland', 8, 8],
  'ES': ['Spain', 1, 1],
  'PL': ['Poland', 40, 42]
}
