countries_dict = {
  'SE': ['Sweden', 2, 2],
  'SG': ['Singapore', 8, 10],
  'IE': ['Ireland', 24, 25],
  'FI': ['Finland', 7, 7],
  'CK': ['Cook Islands', 3, 3],
  'GL': ['Greenland', 2, 2],
  'PL': ['Poland', 41, 43],
  'AE': ['United Arab Emirates', 1, 1],
  'KE': ['Kenya', 1, 1],
  'ZA': ['South Africa', 1, 1],
  'BE': ['Belgium', 33, 35],
  'ZM': ['Zambia', 1, 1],
  'DE': ['Germany', 91, 97],
  'OM': ['Oman', 2, 2],
  'DK': ['Denmark', 7, 7],
  'PK': ['Pakistan', 2, 2],
  'TL': ['East Timor', 1, 1],
  'VU': ['Vanuatu', 4, 4],
  'SB': ['Solomon Islands', 32, 36],
  'KR': ['South Korea', 1, 1],
  'TO': ['Tonga', 5, 5],
  'ES': ['Spain', 1, 1],
  'NL': ['Netherlands', 28, 30],
  'TR': ['Turkey', 62, 74],
  'BI': ['Burundi', 2, 2],
  'GB': ['United Kingdom', 25, 25],
  'CA': ['Canada', 1, 1],
  'AU': ['Australia', 269, 291],
  'ID': ['Indonesia', 20, 21],
  'US': ['United States of America', 6, 6],
  'CN': ['South China Sea Islands (disputed)', 2, 2],
  'NZ': ['New Zealand', 16, 16]
}
