var countries = [
  ['IT', 'Italy', 225, 356],
  ['CA', 'Canada', 2, 2],
  ['CN', 'China', 18, 19],
  ['EE', 'Estonia', 1, 1],
  ['AU', 'Australia', 32, 47],
  ['GB', 'United Kingdom', 9, 16],
  ['CH', 'Switzerland', 10, 11],
  ['ES', 'Spain', 15, 22],
  ['LK', 'Sri Lanka', 1, 1],
  ['IE', 'Ireland', 20, 25],
  ['AT', 'Austria', 1, 1],
  ['FR', 'France', 15, 20],
  ['LV', 'Latvia', 2, 9],
  ['DE', 'Germany', 5, 8],
  ['US', 'United States of America', 41, 44],
  ['LT', 'Lithuania', 1, 2],
  ['GI', 'Gibraltar', 1, 1],
  ['GR', 'Greece', 19, 31],
  ['NL', 'The Netherlands', 1, 2],
  ['RO', 'Romania', 6, 6],
  ['PL', 'Poland', 1, 1],
  ['MX', 'Mexico', 6, 7],
  ['NZ', 'New Zealand', 1, 2],
  ['KZ', 'Kazakhstan', 3, 4],
  ['BS', 'Bahamas', 2, 9],
  ['TR', 'Turkey', 3, 6],
  ['RU', 'Russia', 4, 13],
  ['HR', 'Croatia', 1, 1],
  ['JP', 'Japan', 13, 16],
  ['KR', 'South Korea', 2, 5],
  ['BE', 'Belgium', 2, 2]
]
