countries_dict = {
  'NL': ['Netherlands', 7, 10],
  'ES': ['Spain', 3, 4],
  'GG': ['Guernsey', 9, 10],
  'IT': ['Italy', 17, 20],
  'US': ['United States of America', 1, 4],
  'AT': ['Austria', 1, 2],
  'FR': ['France', 5, 6],
  'CA': ['Canada', 9, 11],
  'JE': ['Jersey', 15, 18],
  'ID': ['Indonesia', 1, 2],
  'MC': ['Monaco', 1, 1],
  'IN': ['India', 1, 1],
  'GB': ['United Kingdom', 2082, 9254],
  'PT': ['Portugal', 18, 33],
  'IE': ['Ireland', 3, 8],
  'GR': ['Greece', 14, 22],
  'CH': ['Switzerland', 1, 3],
  'DE': ['Germany', 1, 1]
}
