countries_dict = {
  'SD': ['Sudan', 1, 1],
  'TH': ['Thailand', 2, 3],
  'RS': ['Serbia', 1, 1],
  'CH': ['Switzerland', 1, 1],
  'JO': ['Jordan', 1, 1],
  'US': ['United States of America', 15, 19],
  'EG': ['Egypt', 1, 1],
  'KI': ['Kiribati', 3, 3],
  'GB': ['United Kingdom', 5, 6],
  'IT': ['Italy', 2, 2],
  'NL': ['Netherlands', 2, 2],
  'ES': ['Spain', 5, 7],
  'LB': ['Lebanon', 2, 2],
  'IN': ['India', 4, 592],
  'TN': ['Tunisia', 1, 1],
  'BE': ['Belgium', 1, 1],
  'RU': ['Russia', 1, 1],
  'GR': ['Greece', 94, 99],
  'BR': ['Brazil', 4, 5]
}
