countries_dict = {
  'TH': ['Thailand', 2, 3],
  'IN': ['India', 4, 594],
  'IT': ['Italy', 2, 2],
  'KI': ['Kiribati', 3, 3],
  'CH': ['Switzerland', 1, 1],
  'RS': ['Serbia', 1, 1],
  'US': ['United States of America', 13, 17],
  'ES': ['Spain', 5, 7],
  'NL': ['Netherlands', 2, 2],
  'GB': ['United Kingdom', 3, 3],
  'BE': ['Belgium', 1, 1],
  'RU': ['Russia', 1, 1],
  'GR': ['Greece', 93, 94],
  'BR': ['Brazil', 4, 5],
  'LB': ['Lebanon', 2, 2],
  'JO': ['Jordan', 1, 1],
  'SD': ['Sudan', 1, 1],
  'TN': ['Tunisia', 1, 1]
}
