countries_dict = {
  'FR': ['France', 20, 20],
  'IN': ['India', 7, 7],
  'CA': ['Canada', 13, 16],
  'DK': ['Denmark', 1, 1],
  'MT': ['Malta', 10, 12],
  'AT': ['Austria', 4, 4],
  'MX': ['Mexico', 2, 3],
  'US': ['United States of America', 279, 350],
  'CZ': ['Czech Republic', 10, 12],
  'IS': ['Iceland', 18, 22],
  'TR': ['Turkey', 5, 5],
  'GR': ['Greece', 1, 3],
  'SE': ['Sweden', 11, 11],
  'KR': ['South Korea', 5, 5],
  'PR': ['Puerto Rico', 1, 1],
  'NL': ['The Netherlands', 8, 8],
  'GB': ['United Kingdom', 1, 1],
  'TW': ['Taiwan', 4, 4],
  'RU': ['Russia', 2, 2],
  'DE': ['Germany', 22, 22],
  'JP': ['Japan', 8, 9],
  'ES': ['Spain', 12, 13],
  'PT': ['Portugal', 14, 18],
  'SG': ['Singapore', 5, 6],
  'CN': ['South China Sea Islands (disputed)', 34, 40]
}
