countries_dict = {
  'IN': ['India', 9, 9],
  'ES': ['Spain', 12, 14],
  'PR': ['Puerto Rico', 1, 1],
  'KR': ['South Korea', 5, 5],
  'CZ': ['Czech Republic', 13, 15],
  'DK': ['Denmark', 1, 1],
  'TW': ['Taiwan', 4, 4],
  'IS': ['Iceland', 22, 27],
  'NL': ['The Netherlands', 8, 8],
  'MX': ['Mexico', 4, 5],
  'TR': ['Turkey', 6, 6],
  'CH': ['Switzerland', 1, 1],
  'US': ['United States of America', 345, 431],
  'GR': ['Greece', 1, 3],
  'CN': ['South China Sea Islands (disputed)', 38, 46],
  'MT': ['Malta', 10, 12],
  'FR': ['France', 29, 30],
  'GB': ['United Kingdom', 1, 1],
  'CA': ['Canada', 14, 18],
  'SG': ['Singapore', 8, 9],
  'AT': ['Austria', 6, 6],
  'DE': ['Germany', 23, 23],
  'JP': ['Japan', 8, 9],
  'PT': ['Portugal', 16, 21],
  'SE': ['Sweden', 11, 11],
  'RU': ['Russia', 3, 3]
}
