countries_dict = {
  'GR': ['Greece', 3, 17],
  'OM': ['Oman', 4, 12],
  'LV': ['Latvia', 6, 8],
  'PT': ['Portugal', 1, 1],
  'CU': ['Cuba', 2, 3],
  'RS': ['Serbia', 3, 4],
  'DE': ['Germany', 13, 32],
  'CA': ['Canada', 1, 1],
  'NL': ['Netherlands', 34, 72],
  'TH': ['Thailand', 6, 15],
  'KZ': ['Kazakhstan', 2, 3],
  'BD': ['Bangladesh', 2, 14],
  'QA': ['Qatar', 1, 3],
  'US': ['United States of America', 29, 42],
  'KR': ['South Korea', 1, 1],
  'BO': ['Bolivia', 4, 14],
  'JP': ['Japan', 1, 2],
  'ZA': ['South Africa', 4, 5],
  'PG': ['Papua New Guinea', 5, 15],
  'BR': ['Brazil', 5, 8],
  'XK': ['Kosovo', 1, 2],
  'AT': ['Austria', 11, 33],
  'NZ': ['New Zealand', 22, 56],
  'IN': ['India', 1, 1],
  'SA': ['Saudi Arabia', 4, 4],
  'EG': ['Egypt', 1, 1],
  'EC': ['Ecuador', 2, 3],
  'AE': ['United Arab Emirates', 3, 7],
  'AL': ['Albania', 1, 1],
  'TW': ['Taiwan', 3, 24],
  'IT': ['Italy', 29, 53],
  'GB': ['United Kingdom', 184, 631],
  'BN': ['Brunei', 3, 4],
  'ES': ['Spain', 38, 72],
  'IS': ['Iceland', 2, 5],
  'LK': ['Sri Lanka', 1, 8],
  'VA': ['Vatican City', 1, 1],
  'CH': ['Switzerland', 7, 11],
  'MT': ['Malta', 2, 4],
  'CN': ['South China Sea Islands (disputed)', 5, 21],
  'AD': ['Andorra', 2, 2],
  'BE': ['Belgium', 1, 2],
  'IE': ['Ireland', 6, 11],
  'FR': ['France', 48, 130],
  'LT': ['Lithuania', 2, 4],
  'SG': ['Singapore', 1, 4],
  'NO': ['Norway', 24, 34],
  'SE': ['Sweden', 1, 2],
  'FI': ['Finland', 2, 4],
  'MM': ['Myanmar', 2, 2],
  'AU': ['Australia', 50, 75]
}
