var countries = [
  ['GB', 'United Kingdom', 150, 532],
  ['PT', 'Portugal', 1, 1],
  ['AU', 'Australia', 50, 75],
  ['US', 'United States of America', 29, 42],
  ['KZ', 'Kazakhstan', 2, 3],
  ['IT', 'Italy', 29, 53],
  ['SA', 'Saudi Arabia', 4, 4],
  ['FR', 'France', 48, 130],
  ['ES', 'Spain', 38, 72],
  ['BR', 'Brazil', 5, 8],
  ['GR', 'Greece', 3, 17],
  ['JP', 'Japan', 1, 2],
  ['OM', 'Oman', 4, 12],
  ['NZ', 'New Zealand', 22, 56],
  ['NL', 'The Netherlands', 34, 72],
  ['EG', 'Egypt', 1, 1],
  ['BE', 'Belgium', 1, 2],
  ['SE', 'Sweden', 1, 2],
  ['MT', 'Malta', 2, 4],
  ['NO', 'Norway', 24, 34],
  ['TH', 'Thailand', 6, 15],
  ['TW', 'Taiwan', 3, 24],
  ['XK', 'Kosovo', 1, 2],
  ['DE', 'Germany', 13, 32],
  ['EC', 'Ecuador', 2, 3],
  ['CH', 'Switzerland', 7, 11],
  ['AT', 'Austria', 11, 33],
  ['BN', 'Brunei Darussalam', 3, 4],
  ['SG', 'Singapore', 1, 4],
  ['AE', 'United Arab Emirates', 3, 7],
  ['LV', 'Latvia', 6, 8],
  ['LT', 'Lithuania', 2, 4],
  ['BO', 'Bolivia', 4, 14],
  ['CU', 'Cuba', 2, 3],
  ['MM', 'Myanmar', 2, 2],
  ['IN', 'India', 1, 1],
  ['BD', 'Bangladesh', 2, 14],
  ['IE', 'Ireland', 6, 11],
  ['FI', 'Finland', 2, 4],
  ['CA', 'Canada', 1, 1],
  ['CN', 'China', 5, 21],
  ['PG', 'Papua New Guinea', 5, 15],
  ['AD', 'Andorra', 2, 2],
  ['VA', 'Vatican City', 1, 1],
  ['KR', 'South Korea', 1, 1],
  ['LK', 'Sri Lanka', 1, 8],
  ['QA', 'Qatar', 1, 3],
  ['IS', 'Iceland', 2, 5],
  ['ZA', 'South Africa', 4, 5],
  ['AL', 'Albania', 1, 1],
  ['RS', 'Serbia', 3, 4]
]
