countries_dict = {
  'GL': ['Greenland', 1, 1],
  'AT': ['Austria', 13, 15],
  'US': ['United States', 546, 607],
  'IT': ['Italy', 2, 2],
  'NZ': ['New Zealand', 111, 120],
  'CN': ['South China Sea Islands (disputed)', 97, 107],
  'HU': ['Hungary', 3, 3],
  'CZ': ['Czechia', 1, 1],
  'DE': ['Germany', 21, 21],
  'JO': ['Jordan', 1, 1],
  'PE': ['Peru', 27, 40],
  'SK': ['Slovakia', 2, 4],
  'BE': ['Belgium', 5, 6],
  'IS': ['Iceland', 49, 53],
  'NA': ['Namibia', 14, 31],
  'AR': ['Argentina', 6, 7],
  'CA': ['Canada', 7, 7],
  'ZA': ['South Africa', 1, 1],
  'CH': ['Switzerland', 8, 8]
}
