countries_dict = {
  'LU': ['Luxembourg', 2, 4],
  'RU': ['Russia', 5, 5],
  'DK': ['Denmark', 2, 3],
  'IN': ['India', 25, 67],
  'ES': ['Spain', 6, 35],
  'CN': ['South China Sea Islands (disputed)', 4, 6],
  'FR': ['France', 91, 146],
  'SG': ['Singapore', 4, 21],
  'MT': ['Malta', 2, 2],
  'TH': ['Thailand', 8, 21],
  'ZA': ['South Africa', 3, 6],
  'US': ['United States of America', 18, 103],
  'CH': ['Switzerland', 3, 10],
  'AT': ['Austria', 6, 18],
  'VA': ['Vatican City', 1, 2],
  'PT': ['Portugal', 9, 14],
  'BE': ['Belgium', 52, 76],
  'CL': ['Chile', 2, 2],
  'NL': ['The Netherlands', 110, 182],
  'IE': ['Ireland', 1, 1],
  'DE': ['Germany', 2, 5],
  'IT': ['Italy', 8, 10],
  'GB': ['United Kingdom', 4, 8],
  'PL': ['Poland', 1, 10],
  'AU': ['Australia', 17, 115],
  'CA': ['Canada', 4, 13],
  'JP': ['Japan', 6, 20],
  'MY': ['Malaysia', 4, 12]
}
