countries_dict = {
  'SE': ['Sweden', 1, 1],
  'DK': ['Denmark', 1, 1],
  'CH': ['Switzerland', 6, 6],
  'US': ['United States of America', 85, 86],
  'CA': ['Canada', 12, 13],
  'ES': ['Spain', 39, 40],
  'FR': ['France', 14, 14],
  'AT': ['Austria', 1, 1],
  'HU': ['Hungary', 2, 2],
  'AD': ['Andorra', 1, 1],
  'BY': ['Belarus', 2, 2],
  'LV': ['Latvia', 1, 1],
  'LT': ['Lithuania', 2, 2],
  'IT': ['Italy', 11, 11],
  'GE': ['Georgia', 9, 10],
  'UA': ['Ukraine', 121, 135],
  'DE': ['Germany', 2, 2],
  'GR': ['Greece', 1, 1],
  'TR': ['Turkey', 9, 9],
  'PT': ['Portugal', 67, 78]
}
