countries_dict = {
  'BE': ['Belgium', 2, 2],
  'US': ['United States of America', 14, 15],
  'SE': ['Sweden', 6, 8],
  'NL': ['Netherlands', 14, 17],
  'EG': ['Egypt', 6, 7],
  'CA': ['Canada', 1, 1],
  'FR': ['France', 96, 130],
  'KE': ['Kenya', 73, 83],
  'MA': ['Morocco', 6, 6],
  'IT': ['Italy', 14, 16],
  'GE': ['Georgia', 15, 15],
  'GB': ['United Kingdom', 17, 17],
  'CN': ['South China Sea Islands (disputed)', 19, 20],
  'DO': ['Dominican Republic', 1, 1],
  'PT': ['Portugal', 5, 6],
  'GR': ['Greece', 1, 1],
  'VA': ['Vatican City', 1, 1],
  'ES': ['Spain', 8, 9]
}
