countries_dict = {
  'ES': ['Spain', 1, 1],
  'IT': ['Italy', 4, 5],
  'FR': ['France', 18, 19],
  'GB': ['United Kingdom', 277, 519],
  'RS': ['Serbia', 1, 1],
  'MA': ['Morocco', 4, 4],
  'CA': ['Canada', 138, 160],
  'MC': ['Monaco', 2, 2],
  'TH': ['Thailand', 4, 4],
  'XK': ['Kosovo', 2, 2],
  'RU': ['Russia', 4, 4],
  'DE': ['Germany', 13, 15],
  'BE': ['Belgium', 1, 1],
  'FI': ['Finland', 5, 5],
  'NO': ['Norway', 2, 2],
  'ID': ['Indonesia', 8, 9],
  'HR': ['Croatia', 3, 9],
  'PT': ['Portugal', 1, 1],
  'US': ['United States of America', 62, 69],
  'NP': ['Nepal', 17, 24],
  'NL': ['The Netherlands', 3, 3],
  'SG': ['Singapore', 5, 6],
  'VN': ['Vietnam', 1, 1],
  'BA': ['Bosnia and Herzegovina', 3, 3],
  'ME': ['Montenegro', 1, 1],
  'GR': ['Greece', 1, 1],
  'SE': ['Sweden', 1, 1],
  'CN': ['South China Sea Islands (disputed)', 15, 18],
  'MY': ['Malaysia', 5, 5],
  'IN': ['India', 2, 4],
  'DK': ['Denmark', 4, 4],
  'IE': ['Ireland', 5, 5],
  'FO': ['Faroe Islands', 6, 6],
  'BS': ['Bahamas', 1, 1]
}
